### ISSUE TITLE
Crashes with Tiff files >4GB

### ISSUE THREAD

**Issue by lillisinthelab** [NICALab/SUPPORT#15]
Congrats on the SUPPORT toolbox! It worked impressively well at denoising our voltage imaging data using the default model. We are currently encountering a problem where SUPPORT crashes while processing Tiff files larger than 4GB. Is this a fundamental limitation? Are there plans to support BigTIFF? For context, our data is 1024x1224, 8-bits, recorded at 200Hz. So, a 4 min recording is in the neighborhood of 60GB. The error message is below. 

Traceback (most recent call last):
  File "C:\Users\2P-user\SUPPORT\src\GUI\test_GUI.py", line 185, in run
    img_one = tifffile.imread(
  File "C:\Users\2P-user\miniconda3\envs\SUPPORT\lib\site-packages\tifffile\tifffile.py", line 1274, in imread
    return tif.asarray(
  File "C:\Users\2P-user\miniconda3\envs\SUPPORT\lib\site-packages\tifffile\tifffile.py", line 4465, in asarray
    pages = pages._getlist(key)
  File "C:\Users\2P-user\miniconda3\envs\SUPPORT\lib\site-packages\tifffile\tifffile.py", line 7788, in _getlist
    pages = [getitem(i, validate=validhash) for i in key]
  File "C:\Users\2P-user\miniconda3\envs\SUPPORT\lib\site-packages\tifffile\tifffile.py", line 7788, in <listcomp>
    pages = [getitem(i, validate=validhash) for i in key]
  File "C:\Users\2P-user\miniconda3\envs\SUPPORT\lib\site-packages\tifffile\tifffile.py", line 7834, in _getitem
    self._seek(key)
  File "C:\Users\2P-user\miniconda3\envs\SUPPORT\lib\site-packages\tifffile\tifffile.py", line 7735, in _seek
    raise IndexError('index out of range')
IndexError: index out of range

**Comment by lillisinthelab** [comment]
....aaaaannd nevermind. It looks like, by default, ImageJ will save a Tiff that is >4GB, but maybe not in the BigTIFF format? When I export from Fiji using the Bioformats Exporter, SUPPORT works as expected.

**Comment by SteveJayH** [comment]
Happy to hear that you resolved the problem. Thanks for providing the solution!
